# Usa a imagem oficial do Nginx (versão alpine para ser mais leve)
FROM nginx:alpine

# Copia o arquivo index.html para a pasta padrão de arquivos estáticos do Nginx
COPY index.html /usr/share/nginx/html/

# Expondo a porta padrão do Nginx
EXPOSE 80